# Generated by Django 3.0.6 on 2020-06-04 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='JobOffer',
        ),
    ]
